webtalk_init -webtalk_dir /home/gab41928/hsc/Project/V2/IP_Core_working/IP_Core_working.sim/sim_1/behav/xsim/xsim.dir/shift_register_x24_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan 20 15:57:58 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0c92da88-2d5b-441e-a572-83320dcee35e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c5777031ead24c7a96f74d0990dfd5f4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "177" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 10 (buster)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4359.597 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1501 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119392_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2104180542 -regid "" -xml /home/gab41928/hsc/Project/V2/IP_Core_working/IP_Core_working.sim/sim_1/behav/xsim/xsim.dir/shift_register_x24_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/gab41928/hsc/Project/V2/IP_Core_working/IP_Core_working.sim/sim_1/behav/xsim/xsim.dir/shift_register_x24_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/gab41928/hsc/Project/V2/IP_Core_working/IP_Core_working.sim/sim_1/behav/xsim/xsim.dir/shift_register_x24_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
